### ISSUE TITLE
TypeError: 'str' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by junhao1999** [open-mmlab/mmskeleton#233]
Hi,when i run the command,it happened

```
junhao@junhao-H370AORUSGAMING3WIFI:~/mmskeleton$ mmskl configs/recognition/st_gcn/kinetics-skeleton/test.yaml --gpus 2 --batch_size 14 --checkpoint st_gcn.ntu-xview-9ba67746.pth
Traceback (most recent call last):
  File "/home/junhao/.local/bin/mmskl", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/junhao/mmskeleton/tools/mmskl", line 68, in <module>
    main()
  File "/home/junhao/mmskeleton/tools/mmskl", line 64, in main
    call_obj(**cfg.processor_cfg)
  File "/home/junhao/mmskeleton/mmskeleton/utils/importer.py", line 20, in call_obj
    return import_obj(name)(**kwargs)
  File "/home/junhao/mmskeleton/mmskeleton/processor/recognition.py", line 16, in test
    num_workers=workers)
  File "/home/junhao/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 219, in __init__
    batch_sampler = BatchSampler(sampler, batch_size, drop_last)
  File "/home/junhao/.local/lib/python3.5/site-packages/torch/utils/data/sampler.py", line 190, in __init__
    "but got batch_size={}".format(batch_size))
ValueError: batch_size should be a positive integer value, but got batch_size=14
junhao@junhao-H370AORUSGAMING3WIFI:~/mmskeleton$ mmskl configs/recognition/st_gcn/kinetics-skeleton/test.yaml --gpus 2
Traceback (most recent call last):
  File "/home/junhao/.local/bin/mmskl", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/junhao/mmskeleton/tools/mmskl", line 68, in <module>
    main()
  File "/home/junhao/mmskeleton/tools/mmskl", line 64, in main
    call_obj(**cfg.processor_cfg)
  File "/home/junhao/mmskeleton/mmskeleton/utils/importer.py", line 20, in call_obj
    return import_obj(name)(**kwargs)
  File "/home/junhao/mmskeleton/mmskeleton/processor/recognition.py", line 25, in test
    model = MMDataParallel(model, device_ids=range(gpus)).cuda()
**TypeError: 'str' object cannot be interpreted as an integer**
```

**Comment by yysijie** [comment]
@junhao1999,
Thank you. We have fixed this issue.
