### ISSUE TITLE
Error while installing mmdet

### ISSUE THREAD

**Issue by joeljosephjin** [open-mmlab/mmskeleton#308]
I was running the following code on a google colab notebook with GPU as runtime:
```
!pip install -q mmcv terminaltables
!pip install -v -e .[optional]
!pip install -r "requirements.txt"
```

which gave me this error:
```
Created temporary directory: /tmp/pip-ephem-wheel-cache-fxb0q_1y
Created temporary directory: /tmp/pip-req-tracker-e35mbbz3
Created requirements tracker '/tmp/pip-req-tracker-e35mbbz3'
Created temporary directory: /tmp/pip-install-u14lvltd
Obtaining file:///content/mmdetection
  Added file:///content/mmdetection to build tracker '/tmp/pip-req-tracker-e35mbbz3'
    Running setup.py (path:/content/mmdetection/setup.py) egg_info for package from file:///content/mmdetection
    Running command python setup.py egg_info
    running egg_info
    writing mmdet.egg-info/PKG-INFO
    writing dependency_links to mmdet.egg-info/dependency_links.txt
    writing requirements to mmdet.egg-info/requires.txt
    writing top-level names to mmdet.egg-info/top_level.txt
    writing manifest file 'mmdet.egg-info/SOURCES.txt'
    /usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py:304: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
  Source in /content/mmdetection has version 1.0rc1+4357697, which satisfies requirement mmdet==1.0rc1+4357697 from file:///content/mmdetection
  Removed mmdet==1.0rc1+4357697 from file:///content/mmdetection from build tracker '/tmp/pip-req-tracker-e35mbbz3'
  Installing extra requirements: 'optional'
  WARNING: mmdet 1.0rc1+4357697 does not provide the extra 'optional'
Requirement already satisfied: mmcv>=0.2.10 in /usr/local/lib/python3.6/dist-packages (from mmdet==1.0rc1+4357697) (0.5.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from mmdet==1.0rc1+4357697) (1.17.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from mmdet==1.0rc1+4357697) (3.2.1)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from mmdet==1.0rc1+4357697) (1.12.0)
Requirement already satisfied: terminaltables in /usr/local/lib/python3.6/dist-packages (from mmdet==1.0rc1+4357697) (3.1.0)
Requirement already satisfied: pycocotools in /usr/local/lib/python3.6/dist-packages (from mmdet==1.0rc1+4357697) (2.0)
Requirement already satisfied: torch>=1.1 in /usr/local/lib/python3.6/dist-packages (from mmdet==1.0rc1+4357697) (1.5.0+cu101)
Requirement already satisfied: torchvision in /usr/local/lib/python3.6/dist-packages (from mmdet==1.0rc1+4357697) (0.6.0+cu101)
Requirement already satisfied: imagecorruptions in /usr/local/lib/python3.6/dist-packages (from mmdet==1.0rc1+4357697) (1.1.0)
Requirement already satisfied: albumentations>=0.3.2 in /usr/local/lib/python3.6/dist-packages (from mmdet==1.0rc1+4357697) (0.4.5)
Requirement already satisfied: addict in /usr/local/lib/python3.6/dist-packages (from mmcv>=0.2.10->mmdet==1.0rc1+4357697) (2.2.1)
Requirement already satisfied: opencv-python>=3 in /usr/local/lib/python3.6/dist-packages (from mmcv>=0.2.10->mmdet==1.0rc1+4357697) (4.1.2.30)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.6/dist-packages (from mmcv>=0.2.10->mmdet==1.0rc1+4357697) (3.13)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->mmdet==1.0rc1+4357697) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib->mmdet==1.0rc1+4357697) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->mmdet==1.0rc1+4357697) (1.2.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->mmdet==1.0rc1+4357697) (2.8.1)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from torch>=1.1->mmdet==1.0rc1+4357697) (0.16.0)
Requirement already satisfied: pillow>=4.1.1 in /usr/local/lib/python3.6/dist-packages (from torchvision->mmdet==1.0rc1+4357697) (7.0.0)
Requirement already satisfied: scikit-image>=0.15 in /usr/local/lib/python3.6/dist-packages (from imagecorruptions->mmdet==1.0rc1+4357697) (0.16.2)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.6/dist-packages (from imagecorruptions->mmdet==1.0rc1+4357697) (1.4.1)
Requirement already satisfied: imgaug<0.2.7,>=0.2.5 in /usr/local/lib/python3.6/dist-packages (from albumentations>=0.3.2->mmdet==1.0rc1+4357697) (0.2.6)
Requirement already satisfied: PyWavelets>=0.4.0 in /usr/local/lib/python3.6/dist-packages (from scikit-image>=0.15->imagecorruptions->mmdet==1.0rc1+4357697) (1.1.1)
Requirement already satisfied: networkx>=2.0 in /usr/local/lib/python3.6/dist-packages (from scikit-image>=0.15->imagecorruptions->mmdet==1.0rc1+4357697) (2.4)
Requirement already satisfied: imageio>=2.3.0 in /usr/local/lib/python3.6/dist-packages (from scikit-image>=0.15->imagecorruptions->mmdet==1.0rc1+4357697) (2.4.1)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.6/dist-packages (from networkx>=2.0->scikit-image>=0.15->imagecorruptions->mmdet==1.0rc1+4357697) (4.4.2)
Installing collected packages: mmdet
  Running setup.py develop for mmdet
    Running command /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/content/mmdetection/setup.py'"'"'; __file__='"'"'/content/mmdetection/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    writing mmdet.egg-info/PKG-INFO
    writing dependency_links to mmdet.egg-info/dependency_links.txt
    writing requirements to mmdet.egg-info/requires.txt
    writing top-level names to mmdet.egg-info/top_level.txt
    writing manifest file 'mmdet.egg-info/SOURCES.txt'
    running build_ext
    building 'mmdet.ops.nms.nms_cuda' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c mmdet/ops/nms/src/nms_cuda.cpp -o build/temp.linux-x86_64-3.6/mmdet/ops/nms/src/nms_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    mmdet/ops/nms/src/nms_cuda.cpp: In function ‘at::Tensor nms(const at::Tensor&, float)’:
    mmdet/ops/nms/src/nms_cuda.cpp:4:39: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
     #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                                           ^
    mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
       CHECK_CUDA(dets);
       ^
    In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:11:0,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/extension.h:4,
                     from mmdet/ops/nms/src/nms_cuda.cpp:2:
    /usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:262:30: note: declared here
       DeprecatedTypeProperties & type() const {
                                  ^~~~
    mmdet/ops/nms/src/nms_cuda.cpp:4:23: error: ‘AT_CHECK’ was not declared in this scope
     #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                           ^
    mmdet/ops/nms/src/nms_cuda.cpp:4:23: note: in definition of macro ‘CHECK_CUDA’
     #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                           ^~~~~~~~
    mmdet/ops/nms/src/nms_cuda.cpp:4:23: note: suggested alternative: ‘DCHECK’
     #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                           ^
    mmdet/ops/nms/src/nms_cuda.cpp:4:23: note: in definition of macro ‘CHECK_CUDA’
     #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                           ^~~~~~~~
    /usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py:304: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-e35mbbz3'
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/content/mmdetection/setup.py'"'"'; __file__='"'"'/content/mmdetection/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 455, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/__init__.py", line 62, in install_given_reqs
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 851, in install
    install_options, global_options, prefix=prefix,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 700, in install_editable
    cwd=self.unpacked_source_directory,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/content/mmdetection/setup.py'"'"'; __file__='"'"'/content/mmdetection/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Requirement already satisfied: mmcv>=0.2.10 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1)) (0.5.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 2)) (1.17.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 3)) (3.2.1)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 4)) (1.12.0)
Requirement already satisfied: terminaltables in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 5)) (3.1.0)
Requirement already satisfied: pycocotools in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 6)) (2.0)
Requirement already satisfied: torch>=1.1 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 7)) (1.5.0+cu101)
Requirement already satisfied: torchvision in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 8)) (0.6.0+cu101)
Requirement already satisfied: imagecorruptions in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 9)) (1.1.0)
Requirement already satisfied: albumentations>=0.3.2 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 10)) (0.4.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.6/dist-packages (from mmcv>=0.2.10->-r requirements.txt (line 1)) (3.13)
Requirement already satisfied: opencv-python>=3 in /usr/local/lib/python3.6/dist-packages (from mmcv>=0.2.10->-r requirements.txt (line 1)) (4.1.2.30)
Requirement already satisfied: addict in /usr/local/lib/python3.6/dist-packages (from mmcv>=0.2.10->-r requirements.txt (line 1)) (2.2.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->-r requirements.txt (line 3)) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->-r requirements.txt (line 3)) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib->-r requirements.txt (line 3)) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->-r requirements.txt (line 3)) (2.8.1)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from torch>=1.1->-r requirements.txt (line 7)) (0.16.0)
Requirement already satisfied: pillow>=4.1.1 in /usr/local/lib/python3.6/dist-packages (from torchvision->-r requirements.txt (line 8)) (7.0.0)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.6/dist-packages (from imagecorruptions->-r requirements.txt (line 9)) (1.4.1)
Requirement already satisfied: scikit-image>=0.15 in /usr/local/lib/python3.6/dist-packages (from imagecorruptions->-r requirements.txt (line 9)) (0.16.2)
Requirement already satisfied: imgaug<0.2.7,>=0.2.5 in /usr/local/lib/python3.6/dist-packages (from albumentations>=0.3.2->-r requirements.txt (line 10)) (0.2.6)
Requirement already satisfied: PyWavelets>=0.4.0 in /usr/local/lib/python3.6/dist-packages (from scikit-image>=0.15->imagecorruptions->-r requirements.txt (line 9)) (1.1.1)
Requirement already satisfied: networkx>=2.0 in /usr/local/lib/python3.6/dist-packages (from scikit-image>=0.15->imagecorruptions->-r requirements.txt (line 9)) (2.4)
Requirement already satisfied: imageio>=2.3.0 in /usr/local/lib/python3.6/dist-packages (from scikit-image>=0.15->imagecorruptions->-r requirements.txt (line 9)) (2.4.1)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.6/dist-packages (from networkx>=2.0->scikit-image>=0.15->imagecorruptions->-r requirements.txt (line 9)) (4.4.2)
```

**Comment by joeljosephjin** [comment]
I ran another fork of this repo, so I'll deal with it there
