### ISSUE TITLE
Unable to get git version

### ISSUE THREAD

**Issue by liunian199** [open-mmlab/mmskeleton#313]
Unable to get git version

**Comment by yysijie** [comment]
Please provide more details.

**Comment by HoSiThien137** [comment]
Traceback (most recent call last):
  File "setup.py", line 161, in <module>
    write_version_py()
  File "setup.py", line 89, in write_version_py
    sha = get_hash()
  File "setup.py", line 75, in get_hash
    raise ImportError('Unable to get git version')
