### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'num_stages'

### ISSUE THREAD

**Issue by trungmanhhuynh** [open-mmlab/mmskeleton#321]
Hi ,

I ran "python mmskl.py pose_demo --gpus 1" and got this error. 

'''
 "Cython.Distutils.old_build_ext does not properly handle dependencies "
which: no hipcc in (/home/manhh/miniconda3/envs/open-mmlab/bin:/usr/local/bin:/home/manhh/github/mmdetection/yes/google-cloud-sdk/bin:/home/manhh/miniconda3/bin:/usr/local/torch/install/bin:/usr/lib64/qt-3.3/bin:/usr/local/mpi/intel/openmpi-1.10.4/bin:/usr/local/maven/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/cuda-10.2/bin:/usr/local/gcc-5.4.0/bin:/opt/ibutils/bin:/home/manhh/.local/bin:/home/manhh/bin:/home/manhh/bin)
Load configuration information from ./configs/pose_estimation/pose_demo.yaml

Pose estimation:
Traceback (most recent call last):
  File "mmskl.py", line 123, in <module>
    main()
  File "mmskl.py", line 117, in main
    call_obj(**cfg.processor_cfg)
  File "/home/manhh/github/mmskeleton/mmskeleton/utils/importer.py", line 24, in call_obj
    return import_obj(type)(**kwargs)
  File "/home/manhh/github/mmskeleton/mmskeleton/processor/pose_demo.py", line 78, in inference
    model = init_pose_estimator(detection_cfg, estimation_cfg, device=0)
  File "/home/manhh/github/mmskeleton/mmskeleton/apis/estimation.py", line 20, in init_pose_estimator
    device='cpu')
  File "/home/manhh/github/mmdetection/mmdet/apis/inference.py", line 33, in init_detector
    model = build_detector(config.model, test_cfg=config.test_cfg)
  File "/home/manhh/github/mmdetection/mmdet/models/builder.py", line 48, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/manhh/github/mmdetection/mmdet/models/builder.py", line 20, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/manhh/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 168, in build_from_cfg
    return obj_cls(**args)
**TypeError: __init__() got an unexpected keyword argument 'num_stages'**
'''

My conda env: 

mmcv                      0.5.8                     <pip>
mmdet                     2.0.0+29f3617             <pip>
mmskeleton                0.7rc1+2aa1be3            <pip>

I did install mmdetection from https://github.com/open-mmlab/mmdetection, and verify that the detection works fine. However, it seems like the integration with mmskeleton do not work. 

Could you please point me to some directions? Thank you

**Comment by trungmanhhuynh** [comment]
Nevermind, I got this resolved. 

Rolling back to pytoch 1.2.0 will work. I close this comment.

**Comment by vivek87799** [comment]
I still have the same error.
can you help me with this?

**Comment by YeTaoY** [comment]
> I still have the same error.
> can you help me with this?

Did you slove the problem? I meet the same error,  reinstall mmdetection is not help, either

**Comment by trungmanhhuynh** [comment]
Did you try with  pytoch 1.2.0 ?

**Comment by YeTaoY** [comment]
> Did you try with pytoch 1.2.0 ?

not yet now

**Comment by YeTaoY** [comment]
I find a sentence in Getting Started:
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# CUDA 10.0
conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch
The higher versions are not covered by tests.
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I am now using pytoch1.3
so what I should do next is obviously....

**Comment by YeTaoY** [comment]
> Did you try with pytoch 1.2.0 ?

I tried with pytorch 1.2.0, but I got new problem
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
(open-mmlab) ty@ubuntu:~/KEYPOINT_GCN/mmskeleton$ python mmskl.py pose_demo
/home/ty/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py:41: UserWarning: Cython.Distutils.old_build_ext does not properly handle dependencies and is deprecated.
  "Cython.Distutils.old_build_ext does not properly handle dependencies "
Load configuration information from ./configs/pose_estimation/pose_demo.yaml

Pose estimation:
Traceback (most recent call last):
  File "mmskl.py", line 123, in <module>
    main()
  File "mmskl.py", line 117, in main
    call_obj(**cfg.processor_cfg)
  File "/home/ty/KEYPOINT_GCN/mmskeleton/mmskeleton/utils/importer.py", line 24, in call_obj
    return import_obj(type)(**kwargs)
  File "/home/ty/KEYPOINT_GCN/mmskeleton/mmskeleton/processor/pose_demo.py", line 78, in inference
    model = init_pose_estimator(detection_cfg, estimation_cfg, device=0)
  File "/home/ty/KEYPOINT_GCN/mmskeleton/mmskeleton/apis/estimation.py", line 18, in init_pose_estimator
    detection_model = mmdet.apis.init_detector(detection_model_file,
  File "/home/ty/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/lazy_import-0.2.2-py3.7.egg/lazy_import/__init__.py", line 156, in __getattribute__
    _load_module(self)
  File "/home/ty/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/lazy_import-0.2.2-py3.7.egg/lazy_import/__init__.py", line 537, in _load_module
    msg.format(**modclass._lazy_import_error_strings)), None)
  File "<string>", line 3, in raise_from
ImportError: mmskeleton.utils.third_party attempted to use a functionality that requires module mmdet.apis, but it couldn't be loaded. **Please install mmdet and retry**.
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

I'm sure that I Successfully installed mmdet .  So what happens

**Comment by YeTaoY** [comment]
> Did you try with pytoch 1.2.0 ?

@trungmanhhuynh I tried with pytorch 1.2.0, but I got new problem

(open-mmlab) ty@ubuntu:~/KEYPOINT_GCN/mmskeleton$ python mmskl.py pose_demo
/home/ty/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py:41: UserWarning: Cython.Distutils.old_build_ext does not properly handle dependencies and is deprecated.
"Cython.Distutils.old_build_ext does not properly handle dependencies "
Load configuration information from ./configs/pose_estimation/pose_demo.yaml

Pose estimation:
Traceback (most recent call last):
File "mmskl.py", line 123, in
main()
File "mmskl.py", line 117, in main
call_obj(**cfg.processor_cfg)
File "/home/ty/KEYPOINT_GCN/mmskeleton/mmskeleton/utils/importer.py", line 24, in call_obj
return import_obj(type)(**kwargs)
File "/home/ty/KEYPOINT_GCN/mmskeleton/mmskeleton/processor/pose_demo.py", line 78, in inference
model = init_pose_estimator(detection_cfg, estimation_cfg, device=0)
File "/home/ty/KEYPOINT_GCN/mmskeleton/mmskeleton/apis/estimation.py", line 18, in init_pose_estimator
detection_model = mmdet.apis.init_detector(detection_model_file,
File "/home/ty/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/lazy_import-0.2.2-py3.7.egg/lazy_import/init.py", line 156, in getattribute
_load_module(self)
File "/home/ty/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/lazy_import-0.2.2-py3.7.egg/lazy_import/init.py", line 537, in _load_module
msg.format(**modclass._lazy_import_error_strings)), None)
File "", line 3, in raise_from
ImportError: mmskeleton.utils.third_party attempted to use a functionality that requires module mmdet.apis, but it couldn't be loaded. Please install mmdet and retry.

I'm sure that I Successfully installed mmdet . So what happens

**Comment by YeTaoY** [comment]
> I still have the same error.
> can you help me with this?

@vivek87799  How did you slove this mmdet installation problem?

**Comment by zimenglan-sysu-512** [comment]
hi @trungmanhhuynh 
do u use mmdet v2.0 or mmdet v2.1 (the newest one)?

**Comment by vivek87799** [comment]
> > I still have the same error.
> > can you help me with this?
> 
> @vivek87799 How did you slove this mmdet installation problem?

I haven't solved it yet

**Comment by monjurulkarim** [comment]
Hi, I am facing the same error. 
CUDA 10.2
Torch 1.5.0
Torch vision 0.6
mmdet 2.4

TypeError: init() got an unexpected keyword argument 'num_stages'

The Traceback is the following:
(base) mmoniruzzama@u108100:~/Monjurul/UString$ bash run_demo.sh demo/000821.mp4
Run feature extraction...
Traceback (most recent call last):
File "demo.py", line 331, in
detector = init_detector(cfg_file, model_file, device=device)
File "/home/stufs1/mmoniruzzama/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmdet-2.4.0-py3.7.egg/mmdet/apis/inference.py", line 34, in init_detector
model = build_detector(config.model, test_cfg=config.test_cfg)
File "/home/stufs1/mmoniruzzama/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmdet-2.4.0-py3.7.egg/mmdet/models/builder.py", line 67, in build_detector
return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
File "/home/stufs1/mmoniruzzama/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmdet-2.4.0-py3.7.egg/mmdet/models/builder.py", line 32, in build
return build_from_cfg(cfg, registry, default_args)
File "/home/stufs1/mmoniruzzama/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 167, in build_from_cfg
return obj_cls(**args)
TypeError: init() got an unexpected keyword argument 'num_stages'
Saved in: demo/000821_feature.npz
Run accident inference...
Traceback (most recent call last):
File "demo.py", line 339, in
from src.Models import UString
File "/data/home/stufs1/mmoniruzzama/Monjurul/UString/src/Models.py", line 10, in
from torch_geometric.utils import remove_self_loops, add_self_loops
File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/torch_geometric/init.py", line 5, in
import torch_geometric.transforms
File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/torch_geometric/transforms/init.py", line 37, in
from .gdc import GDC
File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/torch_geometric/transforms/gdc.py", line 2, in
import numba
File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/init.py", line 45, in
import numba.typed
File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/typed/init.py", line 3, in
from .typeddict import Dict
File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/typed/typeddict.py", line 18, in
@njit
File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/decorators.py", line 224, in njit
return jit(*args, **kws)
File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/decorators.py", line 161, in jit
return wrapper(pyfunc)
File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/decorators.py", line 177, in wrapper
**dispatcher_args)
File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/dispatcher.py", line 576, in init
self.targetctx = self.targetdescr.target_context
File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/targets/registry.py", line 50, in target_context
return self._toplevel_target_context
File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/utils.py", line 381, in get
res = instance.dict[self.name] = self.func(instance)
File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/targets/registry.py", line 34, in _toplevel_target_context
return cpu.CPUContext(self.typing_context)
File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/targets/base.py", line 250, in init
self.init()
File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
return func(*args, **kwargs)
File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/targets/cpu.py", line 49, in init
self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/targets/codegen.py", line 612, in init
self._init(self._llvm_module)
File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/targets/codegen.py", line 621, in _init
tm = target.create_target_machine(**tm_options)
TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'
Saved in: demo/000821_result.npz
Run result visualization...
Traceback (most recent call last):
File "demo.py", line 353, in
all_results = np.load(p.result_file, allow_pickle=True)
File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/lib/npyio.py", line 422, in load
fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'demo/000821_result.npz'
Saved in: demo/000821_vis.avi

**Comment by madeepakkumar1** [comment]
I am facing same issue, Please post the solution if some one has resolved it.

**Comment by trungmanhhuynh** [comment]
If you have a problem with this, you can watch this video and try to see if it works? 
https://www.youtube.com/watch?v=yrAuKUpwKco&ab_channel=HuynhFamilyDiscoveringtheWorld

**Comment by Radleye** [comment]
> I am facing same issue, Please post the solution if some one has resolved it.

did you solve the problem?

**Comment by yuerunyu** [comment]
> Nevermind, I got this resolved.
> 
> Rolling back to pytoch 1.2.0 will work. I close this comment.

@trungmanhhuynh would you share your mmdet-version&mmcv-version?

**Comment by kangwei0529** [comment]
跑通了，需要换一下接口文件

**Comment by Fanthers** [comment]
> 跑通了，需要换一下接口文件

请问你是怎么修复的

**Comment by ya-stack** [comment]
Hi Team, 
I am getting this error while running the Cascade TabNet Code -
TypeError: CascadeRCNN: __init__() got an unexpected keyword argument 'num_stages'
(Dependencies Installed: pip install torch==1.8.0 torchvision==0.9.0, cuda version - 11.2, mmdet: 2.17.0 and mmcv-full==1.3.9)
It would be really great if you can help me in solving the error mentioned above.
Thanks in advance!

**Comment by SNEHA1322** [comment]
> Hi, I am facing the same error. CUDA 10.2 Torch 1.5.0 Torch vision 0.6 mmdet 2.4
> 
> TypeError: init() got an unexpected keyword argument 'num_stages'
> 
> The Traceback is the following: (base) mmoniruzzama@u108100:~/Monjurul/UString$ bash run_demo.sh demo/000821.mp4 Run feature extraction... Traceback (most recent call last): File "demo.py", line 331, in detector = init_detector(cfg_file, model_file, device=device) File "/home/stufs1/mmoniruzzama/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmdet-2.4.0-py3.7.egg/mmdet/apis/inference.py", line 34, in init_detector model = build_detector(config.model, test_cfg=config.test_cfg) File "/home/stufs1/mmoniruzzama/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmdet-2.4.0-py3.7.egg/mmdet/models/builder.py", line 67, in build_detector return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg)) File "/home/stufs1/mmoniruzzama/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmdet-2.4.0-py3.7.egg/mmdet/models/builder.py", line 32, in build return build_from_cfg(cfg, registry, default_args) File "/home/stufs1/mmoniruzzama/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 167, in build_from_cfg return obj_cls(**args) TypeError: init() got an unexpected keyword argument 'num_stages' Saved in: demo/000821_feature.npz Run accident inference... Traceback (most recent call last): File "demo.py", line 339, in from src.Models import UString File "/data/home/stufs1/mmoniruzzama/Monjurul/UString/src/Models.py", line 10, in from torch_geometric.utils import remove_self_loops, add_self_loops File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/torch_geometric/init.py", line 5, in import torch_geometric.transforms File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/torch_geometric/transforms/init.py", line 37, in from .gdc import GDC File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/torch_geometric/transforms/gdc.py", line 2, in import numba File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/init.py", line 45, in import numba.typed File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/typed/init.py", line 3, in from .typeddict import Dict File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/typed/typeddict.py", line 18, in @njit File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/decorators.py", line 224, in njit return jit(*args, **kws) File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/decorators.py", line 161, in jit return wrapper(pyfunc) File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/decorators.py", line 177, in wrapper **dispatcher_args) File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/dispatcher.py", line 576, in init self.targetctx = self.targetdescr.target_context File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/targets/registry.py", line 50, in target_context return self._toplevel_target_context File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/utils.py", line 381, in get res = instance.dict[self.name] = self.func(instance) File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/targets/registry.py", line 34, in _toplevel_target_context return cpu.CPUContext(self.typing_context) File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/targets/base.py", line 250, in init self.init() File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock return func(*args, **kwargs) File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/targets/cpu.py", line 49, in init self._internal_codegen = codegen.JITCPUCodegen("numba.exec") File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/targets/codegen.py", line 612, in init self._init(self._llvm_module) File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numba/targets/codegen.py", line 621, in _init tm = target.create_target_machine(**tm_options) TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug' Saved in: demo/000821_result.npz Run result visualization... Traceback (most recent call last): File "demo.py", line 353, in all_results = np.load(p.result_file, allow_pickle=True) File "/home/stufs1/mmoniruzzama/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/lib/npyio.py", line 422, in load fid = open(os_fspath(file), "rb") FileNotFoundError: [Errno 2] No such file or directory: 'demo/000821_result.npz' Saved in: demo/000821_vis.avi

same error did anyone solve this
