### ISSUE TITLE
question about “mmdet”

### ISSUE THREAD

**Issue by YeTaoY** [open-mmlab/mmskeleton#326]
I have successfully installed mmdet by:

_pip install -r requirements/build.txt
pip install "git+https://github.com/open-mmlab/cocoapi.git#subdirectory=pycocotools"
pip install -v -e ._ 

However, I got next error when I verify that mmskeleton and mmdetection by "python mmskl.py pose_demo --gpus 1" :

_(open-mmlab) ty@ubuntu:~/KEYPOINT_GCN/mmskeleton$ python mmskl.py pose_demo --gpus 1
/home/ty/anaconda3/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py:41: UserWarning: Cython.Distutils.old_build_ext does not properly handle dependencies and is deprecated.
  "Cython.Distutils.old_build_ext does not properly handle dependencies "
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Load configuration information from ./configs/pose_estimation/pose_demo.yaml

Pose estimation:
Traceback (most recent call last):
  File "mmskl.py", line 123, in <module>
    main()
  File "mmskl.py", line 117, in main
    call_obj(**cfg.processor_cfg)
  File "/home/ty/KEYPOINT_GCN/mmskeleton/mmskeleton/utils/importer.py", line 24, in call_obj
    return import_obj(type)(**kwargs)
  File "/home/ty/KEYPOINT_GCN/mmskeleton/mmskeleton/processor/pose_demo.py", line 78, in inference
    model = init_pose_estimator(detection_cfg, estimation_cfg, device=0)
  File "/home/ty/KEYPOINT_GCN/mmskeleton/mmskeleton/apis/estimation.py", line 18, in init_pose_estimator
    detection_model = mmdet.apis.init_detector(detection_model_file,
  File "/home/ty/anaconda3/lib/python3.7/site-packages/lazy_import-0.2.2-py3.7.egg/lazy_import/__init__.py", line 156, in __getattribute__
    _load_module(self)
  File "/home/ty/anaconda3/lib/python3.7/site-packages/lazy_import-0.2.2-py3.7.egg/lazy_import/__init__.py", line 537, in _load_module
    msg.format(**modclass._lazy_import_error_strings)), None)
  File "<string>", line 3, in raise_from
**ImportError: mmskeleton.utils.third_party attempted to use a functionality that requires module mmdet.apis, but it couldn't be loaded. Please install mmdet and retry**._

more information:
1. My mmdetection folde is under mmskeleton folder
2. I notice that the new mmdetection uses PyTorch 1.3+, while mmskeleton uses PyTorch 1.2. 
    Should I turn back to pytorch 1.2

**Comment by happysheep224** [comment]
same error

**Comment by happysheep224** [comment]
I modify the mmskeleton/utils/third_party.py, add "import mmdet "in the first row,but it show me another error:

TypeError: Passed module is not a LazyModule instance.

**Comment by happysheep224** [comment]
My cuda verison is 10.2, is it matter?

**Comment by CamilleMaurice** [comment]
I am having the same trouble

**Comment by happysheep224** [comment]
I have fixed this problem by rollback the verision of mmskeleton to 0.7rc

**Comment by mytk2012** [comment]
> I have fixed this problem by rollback the verision of mmskeleton to 0.7rc
Should mmdet version be 1.0 or others?

**Comment by mytk2012** [comment]
> I have fixed this problem by rollback the verision of mmskeleton to 0.7rc

The latest version of mmskeleton is 0.7?

**Comment by happysheep224** [comment]
@mytk2012 zhe latest version of mmskeleton is 0.7rc1. the version of mmdet I installed is 1.2, because mmdet1.2 support torch1.2.0

**Comment by BozhouZha** [comment]
> I have fixed this problem by rollback the verision of mmskeleton to 0.7rc

Hi there, may I know how you rollback to the 0.7rc version?

**Comment by BozhouZha** [comment]
> > I have fixed this problem by rollback the verision of mmskeleton to 0.7rc
> 
> Hi there, may I know how you rollback to the 0.7rc version?

Solved, nvm.

For friends who may run into the same issue "ImportError: mmskeleton.utils.third_party attempted to use a functionality that requires module mmdet.apis, but it couldn't be loaded. Please install mmdet and retry.", please check your mmcv version via 
$ pip list.

Previously, mine is 1.0.0. I uninstall it via $ pip uninstall mmcv, then $ pip install mmcv==0.4.3 fixed this issue.

**Comment by YLTsai0609** [comment]
> > > I have fixed this problem by rollback the verision of mmskeleton to 0.7rc
> > 
> > 
> > Hi there, may I know how you rollback to the 0.7rc version?
> 
> Solved, nvm.
> 
> For friends who may run into the same issue "ImportError: mmskeleton.utils.third_party attempted to use a functionality that requires module mmdet.apis, but it couldn't be loaded. Please install mmdet and retry.", please check your mmcv version via
> $ pip list.
> 
> Previously, mine is 1.0.0. I uninstall it via $ pip uninstall mmcv, then $ pip install mmcv==0.4.3 fixed this issue.

Successfully installed with following:

```
mmcv                      0.4.3                    pypi_0    pypi
mmdet                     1.0rc1+unknown           pypi_0    pypi
mmskeleton                0.7rc1+82bf68a            dev_0    <develop>
pytorch                   1.2.0           cuda100py37h938c94c_0  
torchvision               0.4.0           cuda100py37hecfc37a_0
cudatoolkit               10.0.130                      0  
```

With Cuda 10.1 on the system path.

 echo $PATH
```
/usr/local/cuda/bin:my_path/anaconda3/envs/py_37_torch_12_open-mmlab/bin:my_path/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

echo $LD_LIBRARY_PATH
`/usr/local/cuda/lib64`
echo $CUDAHOME
`/usr/local/cuda`

**Comment by happysheep224** [comment]
thank you for sharing

**Comment by zjr666** [comment]
> 
> 
> > > I have fixed this problem by rollback the verision of mmskeleton to 0.7rc
> > 
> > 
> > Hi there, may I know how you rollback to the 0.7rc version?
> 
> Solved, nvm.
> 
> For friends who may run into the same issue "ImportError: mmskeleton.utils.third_party attempted to use a functionality that requires module mmdet.apis, but it couldn't be loaded. Please install mmdet and retry.", please check your mmcv version via
> $ pip list.
> 
> Previously, mine is 1.0.0. I uninstall it via $ pip uninstall mmcv, then $ pip install mmcv==0.4.3 fixed this issue.



my mmcv version is 0.4.3, But i still get this error ，How can I solve this problem?

**Comment by Radleye** [comment]
> > > > I have fixed this problem by rollback the verision of mmskeleton to 0.7rc
> > > 
> > > 
> > > Hi there, may I know how you rollback to the 0.7rc version?
> > 
> > 
> > Solved, nvm.
> > For friends who may run into the same issue "ImportError: mmskeleton.utils.third_party attempted to use a functionality that requires module mmdet.apis, but it couldn't be loaded. Please install mmdet and retry.", please check your mmcv version via
> > $ pip list.
> > Previously, mine is 1.0.0. I uninstall it via $ pip uninstall mmcv, then $ pip install mmcv==0.4.3 fixed this issue.
> 
> my mmcv version is 0.4.3, But i still get this error ，How can I solve this problem?

same problem , Did you slove the probelm?

**Comment by Radleye** [comment]
met the same problem, althougth install mmcv0.4.3,but didn't work ,how can i slove the issue

**Comment by Radleye** [comment]
> > > > I have fixed this problem by rollback the verision of mmskeleton to 0.7rc
> > > 
> > > 
> > > Hi there, may I know how you rollback to the 0.7rc version?
> > 
> > 
> > Solved, nvm.
> > For friends who may run into the same issue "ImportError: mmskeleton.utils.third_party attempted to use a functionality that requires module mmdet.apis, but it couldn't be loaded. Please install mmdet and retry.", please check your mmcv version via
> > $ pip list.
> > Previously, mine is 1.0.0. I uninstall it via $ pip uninstall mmcv, then $ pip install mmcv==0.4.3 fixed this issue.
> 
> Successfully installed with following:
> 
> ```
> mmcv                      0.4.3                    pypi_0    pypi
> mmdet                     1.0rc1+unknown           pypi_0    pypi
> mmskeleton                0.7rc1+82bf68a            dev_0    <develop>
> pytorch                   1.2.0           cuda100py37h938c94c_0  
> torchvision               0.4.0           cuda100py37hecfc37a_0
> cudatoolkit               10.0.130                      0  
> ```
> 
> With Cuda 10.1 on the system path.
> 
> echo $PATH
> 
> ```
> /usr/local/cuda/bin:my_path/anaconda3/envs/py_37_torch_12_open-mmlab/bin:my_path/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> ```
> 
> echo $LD_LIBRARY_PATH
> `/usr/local/cuda/lib64`
> echo $CUDAHOME
> `/usr/local/cuda`

same envirment, but still report the error

**Comment by SKBL5694** [comment]
> > > > > I have fixed this problem by rollback the verision of mmskeleton to 0.7rc
> > > > 
> > > > 
> > > > Hi there, may I know how you rollback to the 0.7rc version?
> > > 
> > > 
> > > Solved, nvm.
> > > For friends who may run into the same issue "ImportError: mmskeleton.utils.third_party attempted to use a functionality that requires module mmdet.apis, but it couldn't be loaded. Please install mmdet and retry.", please check your mmcv version via
> > > $ pip list.
> > > Previously, mine is 1.0.0. I uninstall it via $ pip uninstall mmcv, then $ pip install mmcv==0.4.3 fixed this issue.
> > 
> > 
> > Successfully installed with following:
> > ```
> > mmcv                      0.4.3                    pypi_0    pypi
> > mmdet                     1.0rc1+unknown           pypi_0    pypi
> > mmskeleton                0.7rc1+82bf68a            dev_0    <develop>
> > pytorch                   1.2.0           cuda100py37h938c94c_0  
> > torchvision               0.4.0           cuda100py37hecfc37a_0
> > cudatoolkit               10.0.130                      0  
> > ```
> > 
> > 
> > With Cuda 10.1 on the system path.
> > echo $PATH
> > ```
> > /usr/local/cuda/bin:my_path/anaconda3/envs/py_37_torch_12_open-mmlab/bin:my_path/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> > ```
> > 
> > 
> > echo $LD_LIBRARY_PATH
> > `/usr/local/cuda/lib64`
> > echo $CUDAHOME
> > `/usr/local/cuda`
> 
> same envirment, but still report the error

when you reinstall those environment, you should execute `pip install -e .`. So you should run this command 3 times during mmcv, mmdet and mmskeleton

**Comment by YAERxc** [comment]
same problem!how to install mmdet==1.0

**Comment by luiseia** [comment]
> same problem!how to install mmdet==1.0

pip install mmdet==1.0

**Comment by zhoutian160930** [comment]
> > > > > I have fixed this problem by rollback the verision of mmskeleton to 0.7rc
> > > > 
> > > > 
> > > > Hi there, may I know how you rollback to the 0.7rc version?
> > > 
> > > 
> > > Solved, nvm.
> > > For friends who may run into the same issue "ImportError: mmskeleton.utils.third_party attempted to use a functionality that requires module mmdet.apis, but it couldn't be loaded. Please install mmdet and retry.", please check your mmcv version via
> > > $ pip list.
> > > Previously, mine is 1.0.0. I uninstall it via $ pip uninstall mmcv, then $ pip install mmcv==0.4.3 fixed this issue.
> > 
> > 
> > my mmcv version is 0.4.3, But i still get this error ，How can I solve this problem?
> 
> same problem , Did you slove the probelm?

same problem , Did you slove the probelm? from 2025.4.17
