### ISSUE TITLE
Met version problems when I recover the st-gcn demo

### ISSUE THREAD

**Issue by happysheep224** [open-mmlab/mmskeleton#332]
I followed the st-gcn guide, install the required libraries. The last step is python mmskl.py pose_demo, but when I run this command, the screen shows like this:

(open-mmlab) yangyang@tensorsrv:~/mmskeleton$ python mmskl.py pose_demo
/dm0/home/yangyang/.conda/envs/open-mmlab/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py:41: UserWarning: Cython.Distutils.old_build_ext does not properly handle dependencies and is deprecated.
  "Cython.Distutils.old_build_ext does not properly handle dependencies "
/dm0/home/yangyang/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py:64: UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
  'The old API of register_module(module, force=False) '
Load configuration information from ./configs/pose_estimation/pose_demo.yaml

Pose estimation:
Traceback (most recent call last):
  File "mmskl.py", line 123, in <module>
    main()
  File "mmskl.py", line 117, in main
    call_obj(**cfg.processor_cfg)
  File "/dm0/home/yangyang/mmskeleton/mmskeleton/utils/importer.py", line 24, in call_obj
    return import_obj(type)(**kwargs)
  File "/dm0/home/yangyang/mmskeleton/mmskeleton/processor/pose_demo.py", line 78, in inference
    model = init_pose_estimator(detection_cfg, estimation_cfg, device=0)
  File "/dm0/home/yangyang/mmskeleton/mmskeleton/apis/estimation.py", line 20, in init_pose_estimator
    device='cpu')
  File "/dm0/home/yangyang/mmdetection/mmdet/apis/inference.py", line 33, in init_detector
    model = build_detector(config.model, test_cfg=config.test_cfg)
  File "/dm0/home/yangyang/mmdetection/mmdet/models/builder.py", line 48, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/dm0/home/yangyang/mmdetection/mmdet/models/builder.py", line 20, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/dm0/home/yangyang/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 167, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'num_stages'

**Comment by happysheep224** [comment]
https://github.com/open-mmlab/mmskeleton/issues/321

**Comment by happysheep224** [comment]
I found that the latest mmdet require pytorch >1.3, and the latest mmskeleton require pytorch ==1.2.0, so their requirements are conflict. My solution is roll back the mmdet to 1.2.0, in this version, mmdet require pytorch >=1.1。
