### ISSUE TITLE
Custom Skeleton-based Dataset

### ISSUE THREAD

**Issue by xiehaizheng** [open-mmlab/mmskeleton#333]
@yysijie ,hello, sorry to interrupt you, when i train the st-gcn model by:
    mmskl configs/recognition/st_gcn/dataset_example/train.yaml.
And the result:
Load configuration information from configs/recognition/st_gcn/dataset_example/train.yaml
/home/rihuisun/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv-0.6.1-py3.7-linux-x86_64.egg/mmcv/runner/epoch_based_runner.py:168: UserWarning: Runner was deprecated, please use EpochBasedRunner instead
  'Runner was deprecated, please use EpochBasedRunner instead')
/home/rihuisun/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv-0.6.1-py3.7-linux-x86_64.egg/mmcv/runner/base_runner.py:59: UserWarning: batch_processor is deprecated, please implement train_step() and val_step() in the model instead.
  warnings.warn('batch_processor is deprecated, please implement '
Traceback (most recent call last):
  File "/home/rihuisun/anaconda3/envs/open-mmlab/bin/mmskl", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/rihuisun/下载/mmskeleton/tools/mmskl", line 124, in <module>
    main()
  File "/home/rihuisun/下载/mmskeleton/tools/mmskl", line 117, in main
    call_obj(**cfg.processor_cfg)
  File "/home/rihuisun/下载/mmskeleton/mmskeleton/utils/importer.py", line 24, in call_obj
    return import_obj(type)(**kwargs)
  File "/home/rihuisun/下载/mmskeleton/mmskeleton/processor/recognition.py", line 110, in train
    runner = Runner(model, batch_processor, optimizer, work_dir,log_level)
  File "/home/rihuisun/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv-0.6.1-py3.7-linux-x86_64.egg/mmcv/runner/epoch_based_runner.py", line 169, in __init__
    super().__init__(*args, **kwargs)
  File "/home/rihuisun/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv-0.6.1-py3.7-linux-x86_64.egg/mmcv/runner/base_runner.py", line 88, in __init__
    raise TypeError(f'logger must be a logging.Logger object, '
TypeError: logger must be a logging.Logger object, but got <class 'int'>。
I can't solve the problem，TypeError: logger must be a logging.Logger object, but got <class 'int'>。Looking forward to your reply!

**Comment by YeTaoY** [comment]
@xiehaizheng Did you slove this problem? I got the same problem

**Comment by xiehaizheng** [comment]
@YeTaoY Sorry. I didn't solve the problem. If you find a solution, I look forward to your sharing

> @xiehaizheng Did you slove this problem? I got the same problem

**Comment by YeTaoY** [comment]
@xiehaizheng I sloved this problem by transforming "log_level" to "logging.Logger" through "logging.getLogger", in /home/rihuisun/下载/mmskeleton/mmskeleton/processor/recognition.py  before "runner = Runner(model, batch_processor, optimizer, work_dir,log_level)"

**Comment by xiehaizheng** [comment]
@YeTaoY Thank you very much

**Comment by Richard-Codes** [comment]
> @xiehaizheng I sloved this problem by transforming "log_level" to "logging.Logger" through "logging.getLogger", in /home/rihuisun/下载/mmskeleton/mmskeleton/processor/recognition.py before "runner = Runner(model, batch_processor, optimizer, work_dir,log_level)"
n to solve that problem.
pi
There is another solutiop uninstall mmcv
pip install mmcv==0.4.0
