### ISSUE TITLE
Error while excute python setup.py develop

### ISSUE THREAD

**Issue by YanjunChen** [open-mmlab/mmskeleton#345]
I was running this code`python setup.py develop`

while give me error
`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 203, in <module>
    zip_safe=False)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/develop.py", line 38, in run
    self.install_for_development()
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/develop.py", line 155, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 759, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pkg_resources/__init__.py", line 781, in resolve
    replace_conflicting=replace_conflicting
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1064, in best_match
    return self.obtain(req, installer)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1076, in obtain
    return installer(requirement)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 686, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 712, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 897, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1167, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1151, in run_setup
    run_setup(setup_script, args)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-_zh_hd6k/mmcv-1.0.2/setup.py", line 219, in <module>
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    self.run_command("egg_info")
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 297, in run
    self.find_sources()
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 304, in find_sources
    mm.run()
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 535, in run
    self.add_defaults()
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 571, in add_defaults
    sdist.add_defaults(self)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/distutils/command/sdist.py", line 228, in add_defaults
    self._add_defaults_ext()
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/distutils/command/sdist.py", line 311, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 144, in finalize_options
    self.check_extensions_list(self.extensions)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/distutils/command/build_ext.py", line 363, in check_extensions_list
    "each element of 'ext_modules' option must be an "
setuptools.sandbox.UnpickleableException: DistutilsSetupError("each element of 'ext_modules' option must be an Extension instance or 2-tuple")`

what should i do to fix it? 
i am using cuda10.0, pytorch and torchvision as demanded.

**Comment by hafizas101** [comment]
Same issue

**Comment by shah-deven** [comment]
I am facing the same issue

**Comment by liuyangshan** [comment]
same issue here

**Comment by LouisChen0104** [comment]
same issue

**Comment by LouisChen0104** [comment]
I solved this by `pip install mmcv` previously

**Comment by YanjunChen** [comment]
> I solved this by `pip install mmcv` previously

Thanks, it worked, and for avoiding further errors i run 
`pip install mmcv==0.4.0`
