### ISSUE TITLE
question about run python main.py demo_offline 

### ISSUE THREAD

**Issue by KrisLee512** [open-mmlab/mmskeleton#384]
I use the old STGCN model,when I run the command"python main.py demo_offline ",I encountered the problem 
" warnings.warn("Setting attributes on ParameterList is not supported.")
Starting OpenPose Python Wrapper...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    p.start()
  File "/home/llb/codes/ST_source/st-gcn/processor/demo_offline.py", line 31, in start
    video, data_numpy = self.pose_estimation()
  File "/home/llb/codes/ST_source/st-gcn/processor/demo_offline.py", line 137, in pose_estimation
    opWrapper.emplaceAndPop([datum])
TypeError: emplaceAndPop(): incompatible function arguments. The following argument types are supported:
    1. (self: openpose.pyopenpose.WrapperPython, arg0: std::vector<std::shared_ptr<op::Datum>, std::allocator<std::shared_ptr<op::Datum> > >) -> bool

Invoked with: <openpose.pyopenpose.WrapperPython object at 0x7f7101f58cb0>, [<openpose.pyopenpose.Datum object at 0x7f7101f586f0>]

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module."
how to fix the bug,thanks

**Comment by yuerunyu** [comment]
@KrisLee512 you should fix /home/llb/codes/ST_source/st-gcn/processor/demo_offline.py", line 137 :opWrapper.emplaceAndPop([datum]) is opWrapper.emplaceAndPop(op.VectorDatum([datum])).

**Comment by whf9527** [comment]
> @KrisLee512 you should fix /home/llb/codes/ST_source/st-gcn/processor/demo_offline.py", line 137 :opWrapper.emplaceAndPop([datum]) is opWrapper.emplaceAndPop(op.VectorDatum([datum])).

thanks，it work for me.
