### ISSUE TITLE
OSError: CUDA is required to compile MMSkeleton!

### ISSUE THREAD

**Issue by SKBL5694** [open-mmlab/mmskeleton#393]
I found the same issue in #310 . In that issue, the suggestion is to choose the correct CUDA version according to the pytorch version and the example is the same as the guide.
But I do follow the guide and I found the same error. My system is linux  with ubuntu 16.04, and I use the command `conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch`. And I use `nvcc -V` to check my cuda version which is ''Cuda compilation tools, release 10.0, V10.0.130'' and the cudnn is 7.6.2. I think my environment is same as the suggestion, but it still raise the error: 
"
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-10.0'
Traceback (most recent call last):
  File "setup.py", line 197, in <module>
    include_dirs=[np.get_include()]),
  File "setup.py", line 134, in make_cuda_ext
    raise EnvironmentError('CUDA is required to compile MMSkeleton!')
OSError: CUDA is required to compile MMSkeleton!
"
I don't know how to deal with this, can you help me?

**Comment by SKBL5694** [comment]
@yysijie

**Comment by Liyato** [comment]
我也不知道，希望赐教

**Comment by rosegit-lab** [comment]
any updates?

**Comment by NANDISHSHAH** [comment]
Hi any  update on this
