### ISSUE TITLE
How to make action recognition result visualization

### ISSUE THREAD

**Issue by SKBL5694** [open-mmlab/mmskeleton#398]
How to generate action recognition gif like the demo in ''mmskeleton/demo/recognition

**Comment by MaarufB** [comment]
Bro did you figure that out? I am still trying on how to generate one.

**Comment by SKBL5694** [comment]
> Bro did you figure that out? I am still trying on how to generate one.

Yes, I've nailed it. But I've finished my work this week. If you're interested in it, maybe I can share you my experience on it during my working time.

**Comment by MaarufB** [comment]
Yes bro I'm so interested. I'd been trying look for that source, I would be thankful if you could show me how. 'Till now still working on it but nothings work.

**Comment by SKBL5694** [comment]
> Yes bro I'm so interested. I'd been trying look for that source, I would be thankful if you could show me how. 'Till now still working on it but nothings work.

I'm glad to help you about that if I can. But I'm not in my work place now. I think I can give you some help two days later. Because the whole process is a bit complicated. So I want to know if you understand Chinese, or if you use WeChat or other communication software that can communicate in real time, if so, it will make our communication more convenient.

**Comment by MaarufB** [comment]
I can't understand chinese bro, but I am working for a taiwanese software company. Okay bro I'll try to  install WeChat. Thanks for the concern by the way.

**Comment by MaarufB** [comment]
@SKBL5694 hello bro. Did you use openpose for action recoginiton using mmskeleton?

**Comment by SKBL5694** [comment]
> @SKBL5694 hello bro. Did you use openpose for action recoginiton using mmskeleton?

I do use openpose. Actually, I use the previous version of mmskeleton called st-gcn to visualize the result.

**Comment by MaarufB** [comment]
Is it possible to use the current mmskeleton to visualize the video result for action recognition? And also the pose_demo for mmskeleton doesn't include the action recognition.

**Comment by SKBL5694** [comment]
> Is it possible to use the current mmskeleton to visualize the video result for action recognition? And also the pose_demo for mmskeleton doesn't include the action recognition.

Good question. Based on my understanding of this framework, I probably say no. Because in the old version(st-gcn), there is a off-the-shelf script which supports train,test,visualization(both real-time and offline). If you use mmskeleton, you can not use this script.

**Comment by MaarufB** [comment]
Ohh I seee. Thanks for saving my time bro. Can I use the st_gcn under the mmskeleton repo "deprecated/origin_stgcn_repo" ? . Thanks once again bro.

**Comment by SKBL5694** [comment]
> Ohh I seee. Thanks for saving my time bro. Can I use the st_gcn under the mmskeleton repo "deprecated/origin_stgcn_repo" ? . Thanks once again bro.

I'm not sure about that. I do the visualization by this [https://github.com/yysijie/st-gcn].

**Comment by MaarufB** [comment]
Thanks for the info bro. You really help me a lot.

**Comment by SKBL5694** [comment]
> Thanks for the info bro. You really help me a lot.

My pleasure.

**Comment by MaarufB** [comment]
Bro, How about the training of own dataset?

**Comment by SKBL5694** [comment]
> Bro, How about the training of own dataset?
Two tips.
First, you should know st-gcn use two kinds of dataset: kinetics and NTU-RGB-D. The former is 18 joints per person with three dimensions of coordinates :(x,y,c) c is the confidence of the openpose output. And the latter has 25 joints per person with three dimensions which the third coordinate is z instead of confidence. Interestingly, both of them can be acceptted to the net. Though I'm a little confused about this operation, the paper also mentions it in 3.2, paragraph 2 and 3.
Second, so you can choose any format(18 joints with confidence or 25 joints with z) you like to build you own dataset. You can refer to these 2 files [NTU dataset](https://raw.githubusercontent.com/yysijie/st-gcn/master/tools/ntu_gendata.py) and [Kinetics dataset](https://raw.githubusercontent.com/yysijie/st-gcn/master/tools/kinetics_gendata.py) to build your own dataset.

**Comment by SKBL5694** [comment]
> Bro, How about the training of own dataset?

Two tips.
First, you should know st-gcn use two kinds of dataset: kinetics and NTU-RGB-D. The former is 18 joints per person with three dimensions of coordinates :(x,y,c) c is the confidence of the openpose output. And the latter has 25 joints per person with three dimensions which the third coordinate is z instead of confidence. Interestingly, both of them can be acceptted to the net. Though I'm a little confused about this operation, the paper also mentions it in 3.2, paragraph 2 and 3.
Second, so you can choose any format(18 joints with confidence or 25 joints with z) you like to build you own dataset. You can refer to these 2 files NTU dataset and Kinetics dataset to build your own dataset.

**Comment by MaarufB** [comment]
Sorry for the late response bro. May I know how did you build your own dataset? I was just following the given procedure on how to build own dataset but something's not right when i ran the training script.

**Comment by SKBL5694** [comment]
> Sorry for the late response bro. May I know how did you build your own dataset? I was just following the given procedure on how to build own dataset but something's not right when i ran the training script.

Emm... I don't know about 'the given procedure on how to build own dataset'. For me, I use openpose to extract joints data from my own videos(have extracted to frames). Then I write a script to change the openpose output to an binary file to feed the net. It's a hard and painful work, I'm working on this script too.

**Comment by MaarufB** [comment]
Actually I followed this one https://github.com/open-mmlab/mmskeleton/blob/master/doc/CUSTOM_DATASET.md. seems not workable doesn't prompt the training loss

**Comment by SKBL5694** [comment]
> Actually I followed this one https://github.com/open-mmlab/mmskeleton/blob/master/doc/CUSTOM_DATASET.md. seems not workable doesn't prompt the training loss

Do you mean that you have generated own dataset's .json file like this?
{
    "info":
        {
            "video_name": "skateboarding.mp4",
            "resolution": [340, 256],
            "num_frame": 300,
            "num_keypoints": 17,
            "keypoint_channels": ["x", "y", "score"],
            "version": "1.0"
        },
    "annotations":
        [
            {
                "frame_index": 0,
                "id": 0,
                "person_id": null,
                "keypoints": [[x, y, score], [x, y, score], ...]
            },
            ...
        ],
    "category_id": 0,
}

**Comment by MaarufB** [comment]
Yes bro.

**Comment by SKBL5694** [comment]
> Yes bro.

And you are using mmskleton not st-gcn to train, am I right?

**Comment by MaarufB** [comment]
Yes bro, Sorry, I wanna try it and if does'nt work I'll use st-gcn.

**Comment by SKBL5694** [comment]
> Yes bro, Sorry, I wanna try it and if does'nt work I'll use st-gcn.

Relax,bro, I didn't mean to blame you. 
I am not familiar with mmskeleton, because I want to visualize my result and make a real-time recognition program.But mmskeleton don't support those operations. So if you have these questions, I suggest you to search 'loss' in the issues. I remember during my searching for answers of my problem(loss do not decrease), I've seen similar questions as yours. If you really want to train with mmskeleton and make visualization #291 may be helpful.(though I can not follow those steps successfully)

**Comment by SKBL5694** [comment]
> Yes bro, Sorry, I wanna try it and if does'nt work I'll use st-gcn.

Relax,bro, I didn't mean to blame you.
I am not familiar with mmskeleton, because I want to visualize my result and make a real-time recognition program.But mmskeleton don't support those operations. So if you have these questions, I suggest you to search 'loss' in the issues. I remember during my searching for answers of my problem, I've seen similar questions as yours(loss do not decrease). If you really want to train with mmskeleton and make visualization #291 may be helpful.(though I can not follow those steps successfully)

**Comment by MaarufB** [comment]
Okay bro thanks. I really got stuck of this and wanna try your tips later I think. Thanks bro

**Comment by zren2** [comment]
> > Bro, How about the training of own dataset?
> 
> Two tips.
> First, you should know st-gcn use two kinds of dataset: kinetics and NTU-RGB-D. The former is 18 joints per person with three dimensions of coordinates :(x,y,c) c is the confidence of the openpose output. And the latter has 25 joints per person with three dimensions which the third coordinate is z instead of confidence. Interestingly, both of them can be acceptted to the net. Though I'm a little confused about this operation, the paper also mentions it in 3.2, paragraph 2 and 3.
> Second, so you can choose any format(18 joints with confidence or 25 joints with z) you like to build you own dataset. You can refer to these 2 files NTU dataset and Kinetics dataset to build your own dataset.

Hi bro, I have installed the st-gcn and I can run the demo code,  but I want to use the NTU-RGB-D model to run the demo,I get  
the following errors:
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    p = Processor(sys.argv[2:])
  File "/home/weilong/st-gcn/processor/io.py", line 28, in __init__
    self.load_weights()
  File "/home/weilong/st-gcn/processor/io.py", line 75, in load_weights
    self.arg.ignore_weights)
  File "/usr/local/lib/python3.6/dist-packages/torchlight-1.0-py3.6.egg/torchlight/io.py", line 89, in load_weights
    
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Model:
	size mismatch for A: copying a param with shape torch.Size([3, 25, 25]) from checkpoint, the shape in current model is torch.Size([3, 18, 18]).
	size mismatch for data_bn.weight: copying a param with shape torch.Size([75]) from checkpoint, the shape in current model is torch.Size([54]).
	size mismatch for data_bn.bias: copying a param with shape torch.Size([75]) from checkpoint, the shape in current model is torch.Size([54]).
	size mismatch for data_bn.running_mean: copying a param with shape torch.Size([75]) from checkpoint, the shape in current model is torch.Size([54]).
	size mismatch for data_bn.running_var: copying a param with shape torch.Size([75]) from checkpoint, the shape in current model is torch.Size([54]).
	size mismatch for edge_importance.0: copying a param with shape torch.Size([3, 25, 25]) from checkpoint, the shape in current model is torch.Size([3, 18, 18]).
	size mismatch for edge_importance.1: copying a param with shape torch.Size([3, 25, 25]) from checkpoint, the shape in current model is torch.Size([3, 18, 18]).
	size mismatch for edge_importance.2: copying a param with shape torch.Size([3, 25, 25]) from checkpoint, the shape in current model is torch.Size([3, 18, 18]).
	size mismatch for edge_importance.3: copying a param with shape torch.Size([3, 25, 25]) from checkpoint, the shape in current model is torch.Size([3, 18, 18]).
	size mismatch for edge_importance.4: copying a param with shape torch.Size([3, 25, 25]) from checkpoint, the shape in current model is torch.Size([3, 18, 18]).
	size mismatch for edge_importance.5: copying a param with shape torch.Size([3, 25, 25]) from checkpoint, the shape in current model is torch.Size([3, 18, 18]).

do you know what's the problem?
我也是一个中国学生，如果方便的请加一下我微信13735698625，谢谢！

**Comment by ChalsonLee** [comment]
> 
> 
> > 兄弟，如何训练自己的数据集？
> 
> 两个提示。
> 首先，您应该知道st-gcn使用两种数据集：动力学数据集和NTU-RGB-D。 前者是每人18个关节，具有三个维度的坐标：（x，y，c）c是开放姿势输出的置信度。 后者每个人有25个关节，三个维度，第三个坐标是z而不是置信度。 有趣的是，它们两者都可以被网所接受。 尽管我对此操作有些困惑，但本文还在3.2的第2段和第3段中提到了此操作。
> 其次，您可以选择自己喜欢的任何格式（18个置信度的关节或25个带z的关节）来构建自己的数据集。 您可以参考这两个文件NTU数据集和Kinetics数据集来构建自己的数据集。



> 
> 
> > Bro, How about the training of own dataset?
> 
> Two tips.
> First, you should know st-gcn use two kinds of dataset: kinetics and NTU-RGB-D. The former is 18 joints per person with three dimensions of coordinates :(x,y,c) c is the confidence of the openpose output. And the latter has 25 joints per person with three dimensions which the third coordinate is z instead of confidence. Interestingly, both of them can be acceptted to the net. Though I'm a little confused about this operation, the paper also mentions it in 3.2, paragraph 2 and 3.
> Second, so you can choose any format(18 joints with confidence or 25 joints with z) you like to build you own dataset. You can refer to these 2 files NTU dataset and Kinetics dataset to build your own dataset.



> 
> 
> > Bro, How about the training of own dataset?
> 
> Two tips.
> First, you should know st-gcn use two kinds of dataset: kinetics and NTU-RGB-D. The former is 18 joints per person with three dimensions of coordinates :(x,y,c) c is the confidence of the openpose output. And the latter has 25 joints per person with three dimensions which the third coordinate is z instead of confidence. Interestingly, both of them can be acceptted to the net. Though I'm a little confused about this operation, the paper also mentions it in 3.2, paragraph 2 and 3.
> Second, so you can choose any format(18 joints with confidence or 25 joints with z) you like to build you own dataset. You can refer to these 2 files NTU dataset and Kinetics dataset to build your own dataset.

In the kinetics 3 dimensions of coordinates :(x,y,c)，why x,y less than 1?looking forward to your reply,thnks

**Comment by ChalsonLee** [comment]
> 
> 
> > Bro, How about the training of own dataset?
> 
> Two tips.
> First, you should know st-gcn use two kinds of dataset: kinetics and NTU-RGB-D. The former is 18 joints per person with three dimensions of coordinates :(x,y,c) c is the confidence of the openpose output. And the latter has 25 joints per person with three dimensions which the third coordinate is z instead of confidence. Interestingly, both of them can be acceptted to the net. Though I'm a little confused about this operation, the paper also mentions it in 3.2, paragraph 2 and 3.
> Second, so you can choose any format(18 joints with confidence or 25 joints with z) you like to build you own dataset. You can refer to these 2 files NTU dataset and Kinetics dataset to build your own dataset.

In the kinetics 3 dimensions of coordinates :(x,y,c)，why x,y less than 1?looking forward to your reply,thanks

**Comment by SKBL5694** [comment]
> In the kinetics 3 dimensions of coordinates :(x,y,c)，why x,y less than 1?looking forward to your reply,thanks

Do you mean st-gcn?

**Comment by ChalsonLee** [comment]
> > In the kinetics 3 dimensions of coordinates :(x,y,c)，why x,y less than 1?looking forward to your reply,thanks
> 
> Do you mean st-gcn?

yes, when I training st-gcn on kinects dataset.

**Comment by SKBL5694** [comment]
> > > In the kinetics 3 dimensions of coordinates :(x,y,c)，why x,y less than 1?looking forward to your reply,thanks
> > 
> > 
> > Do you mean st-gcn?
> 
> yes, when I training st-gcn on kinects dataset.
Maybe this will be helpful.
https://github.com/yysijie/st-gcn/blob/221c0e152054b8da593774c0d483e59befdb9061/processor/demo_offline.py#L143-L147

**Comment by ChalsonLee** [comment]
> > > In the kinetics 3 dimensions of coordinates :(x,y,c)，why x,y less than 1?looking forward to your reply,thanks
> > 
> > 
> > Do you mean st-gcn?
> 
> yes, when I training st-gcn on kinects dataset.
> Maybe this will be helpful.
> https://github.com/yysijie/st-gcn/blob/221c0e152054b8da593774c0d483e59befdb9061/processor/demo_offline.py#L143-L147

thanks a lot

**Comment by SKBL5694** [comment]
> thanks a lot

：）

**Comment by d0683228** [comment]
@SKBL5694 hi
I am studying  st-gcn  recently and I already train a new model with my own dataset ( with mmskeleton )
now I want to visualize the video result  with my model .pth file ( with old version st-gcn )
but I don't know the actual step
can you provide me more detail step  so I can follow?  thx

**Comment by SKBL5694** [comment]
> @SKBL5694 hi
> I am studying st-gcn recently and I already train a new model with my own dataset ( with mmskeleton )
> now I want to visualize the video result with my model .pth file ( with old version st-gcn )
> but I don't know the actual step
> can you provide me more detail step so I can follow? thx

Sry, I don't use the framework 'mmskeleton', I use st-gcn to train and visualize the result.

**Comment by Donny2333** [comment]
@SKBL5694 
Thanks for your guidance. I have successfully trained and tested my own dataset (with mmskeleton).
And here is my test result, it's pretty cool.

`
Top 1: 97.86% Top 5: 100.00%
`

But, when I use st-gcn to visualize. It shows an obvious mistake. Even the video that is trained. 
eg. I transfer a video into the model, that is someone waves his hand to the left. But the vote doesn't show the WAVE_LEFT label.

I'm puzzled. Did I miss something?
Hope for your advice.

**Comment by SKBL5694** [comment]
@Donny2333  I guess you use the test config file named 'demo_offline' , am I right?

**Comment by SKBL5694** [comment]
@Donny2333 BTW, I may not be able to reply to github messages in time, if you are in a hurry, you can add my wechat(refer to my profile), if not, we can discuss it here for future reference. It's up to you.

**Comment by Donny2333** [comment]
@SKBL5694 
Fantastic! My Email is  aiiili@qq.com
Maybe, it's not convenient to leave our personal information here.
Hope to get your understanding.

**Comment by Liqi255** [comment]
Hello, I am studying mmskeleton or st-gcn recently. I seem to see hope through your answers. I urgently need your help. There are many questions to ask. It may not be particularly convenient to use GitHub. Maybe I can add you WeChat or email. Thank you again!

**Comment by zren2** [comment]
Hi, you'd better add my wechat (13735698625).I use it everyday.

Yong.

**Comment by lakpa-tamang9** [comment]
How much fps did you get in real time testing?

**Comment by zren2** [comment]
atound 20.

**Comment by xiaoming970115** [comment]
@zren2  would  you tell me how to visualize using hrnet  instead of  using openpose API ? I need your help
