### ISSUE TITLE
Video not found while building jsons for my custom videos

### ISSUE THREAD

**Issue by Abdelazizmuhmd** [open-mmlab/mmskeleton#402]
I upload 2 videos in the data_exmaple dir, and i changed the category_annoation  to match my classes . and i run the command :
!mmskl configs/utils/build_dataset_example.yaml 
then the 2 jsons are created but this error appears, anyone know how can i solve it ? 
Note: i still didn't change my videos format to match any config file.

Load configuration information from configs/utils/build_dataset_example.yaml
[                                                  ] 0/3, elapsed: 0s, ETA:/usr/local/lib/python3.7/dist-packages/mmdet/apis/inference.py:40: UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
/usr/local/lib/python3.7/dist-packages/mmdet/apis/inference.py:40: UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
[> ] 2/3, 0.0 task/s, elapsed: 299s, ETA:   150sTraceback (most recent call last):
  File "/usr/local/bin/mmskl", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/content/mmskeleton/tools/mmskl", line 123, in <module>
    main()
  File "/content/mmskeleton/tools/mmskl", line 117, in main
    call_obj(**cfg.processor_cfg)
  File "/content/mmskeleton/mmskeleton/utils/importer.py", line 24, in call_obj
    return import_obj(type)(**kwargs)
  File "/content/mmskeleton/mmskeleton/processor/skeleton_dataset.py", line 74, in build
    reader = mmcv.VideoReader(os.path.join(video_dir, video_file))
  File "/usr/local/lib/python3.7/dist-packages/mmcv/video/io.py", line 65, in __init__
    check_file_exist(filename, 'Video file not found: ' + filename)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/path.py", line 25, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: Video file not found: resource/data_example/.ipynb_checkpoints
Process Process-4:
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/content/mmskeleton/mmskeleton/processor/skeleton_dataset.py", line 23, in worker
    idx, image = inputs.get()
  File "<string>", line 2, in get
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 819, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/content/mmskeleton/mmskeleton/processor/skeleton_dataset.py", line 23, in worker
    idx, image = inputs.get()
  File "<string>", line 2, in get
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 819, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

**Comment by mejdidallel** [comment]
did you solve the problem ?
