### ISSUE TITLE
python setup.py develop Getting errors

### ISSUE THREAD

**Issue by Malithi-gif** [open-mmlab/mmskeleton#405]
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by vasanth4224** [comment]
Traceback (most recent call last):
  File "setup.py", line 72, in get_hash
    from mmskeleton.version import __version__
  File "D:\Human_Detection_with_Cellular_Phone\Skeleton_Tracking_Program\samples\python\mmskeleton-master\mmskeleton\__init__.py", line 1, in <module>
    from . import utils
  File "D:\Human_Detection_with_Cellular_Phone\Skeleton_Tracking_Program\samples\python\mmskeleton-master\mmskeleton\utils\__init__.py", line 3, in <module>
    from .checkpoint import load_checkpoint, get_mmskeleton_url, cache_checkpoint
  File "D:\Human_Detection_with_Cellular_Phone\Skeleton_Tracking_Program\samples\python\mmskeleton-master\mmskeleton\utils\checkpoint.py", line 1, in <module>
    from mmcv.runner import load_checkpoint as mmcv_load_checkpoint
ModuleNotFoundError: No module named 'mmcv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 161, in <module>
    write_version_py()
  File "setup.py", line 89, in write_version_py
    sha = get_hash()
  File "setup.py", line 75, in get_hash
    raise ImportError('Unable to get git version')
ImportError: Unable to get git version


I got error... anyone can give me suggestions?

**Comment by shelly-xue** [comment]
@vasanth4224 hi  I have the same question with you.Did you have solved it?

**Comment by vasanth4224** [comment]
@shelly-xue hi.. no did not solve it. if you solve then let me know.
I am also trying...

**Comment by Easonshow** [comment]
@vasanth4224  I have the same question with you.Have you solved it now?

**Comment by Easonshow** [comment]
I downgraded mvcc to version 0.4.3 , excuting the command"cd mmskeleton/ops  make all "  solve this problem

**Comment by vasanth4224** [comment]
> I downgraded mvcc to version 0.4.3 , excuting the command"cd mmskeleton/ops make all " solve this problem

Thank you @Easonshow

**Comment by vasanth4224** [comment]
> I downgraded mvcc to version 0.4.3 , excuting the command"cd mmskeleton/ops make all " solve this problem

@Easonshow  mvcc or mmcv ?

**Comment by Panlelaila** [comment]
Did you solved the problem? I have the same problem

**Comment by vasanth4224** [comment]
@Panlelaila I didn't solve this problem. If you have any idea then let me know.

**Comment by vasanth4224** [comment]
> error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe' failed with exit status 2

Hi @Malithi-gif .. did you solve this error... If you solved the error then let me know.

**Comment by Donny2333** [comment]
Maybe you could try ubuntu system.  As I can see, this project doesn't support Windows system.

**Comment by deepxiaobai** [comment]
Decompress the code and execute 'cd mmskeleton' and 'python setup.py develop'

**Comment by BaochaoZhu** [comment]
> Decompress the code and execute 'cd mmskeleton' and 'python setup.py develop'
'cd mmskeleton' ，I can not find setup.py,could you tell me more about this,thank you
