### ISSUE TITLE
train myself model error: Invalid device id

### ISSUE THREAD

**Issue by mahui97** [open-mmlab/mmskeleton#433]
I run the commond:
`$ mmskl configs/recognition/st_gcn_aaai18/ntu-rgbd-xsub/train.yaml`
but get a error as:

Load configuration information from configs/recognition/st_gcn_aaai18/ntu-rgbd-xsub/train.yaml
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/open-mmlab/bin/mmskl", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/ubuntu/mahui/mmskeleton/tools/mmskl", line 123, in <module>
    main()
  File "/home/ubuntu/mahui/mmskeleton/tools/mmskl", line 117, in main
    call_obj(**cfg.processor_cfg)
  File "/home/ubuntu/mahui/mmskeleton/mmskeleton/utils/importer.py", line 24, in call_obj
    return import_obj(type)(**kwargs)
  File "/home/ubuntu/mahui/mmskeleton/mmskeleton/processor/recognition.py", line 105, in train
    model = MMDataParallel(model, device_ids=range(gpus)).cuda()
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 133, in __init__
    _check_balance(self.device_ids)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 19, in _check_balance
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 19, in <listcomp>
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/cuda/__init__.py", line 318, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id

so, how to solve this problem?

**Comment by mahui97** [comment]
oh, I resolved this problem. 
The command is:
`$ mmskl configs/recognition/st_gcn_aaai18/ntu-rgbd-xsub/train.yaml --gpus 1`.
Without `--gpus 1`, the computer don't know "devices_id" list.
If I add `--gpus 1`, the computer will find GPU to execute the program.
