### ISSUE TITLE
question about run python main.py demo_offline

### ISSUE THREAD

**Issue by hhaaahaaaas1221** [open-mmlab/mmskeleton#463]
I encountered an error while trying to test demo_offline.The error is as follows：
`(pytorch) E:\Ruan\torch\st-gcn-master\st-gcn-master>python main.py demo_offline --video ./resource/media/clean_and_jerk.mp4 --openpose openpose-master/openpose-master/build
Can not find Openpose Python API.
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    p.start()
  File "E:\Ruan\torch\st-gcn-master\st-gcn-master\processor\demo_offline.py", line 31, in start
    video, data_numpy = self.pose_estimation()
TypeError: 'NoneType' object is not iterable`
I have no choice but to follow the online tutorial and make changes that are still invalid

**Comment by LYHNB** [comment]
I have the same problem，have you worked out?
